version: '3'

services:
  rest:
    depends_on:
      - db
      #- pgadmin
    build:
      context: ./rest
      dockerfile: Dockerfile
    ports:
      - 8081:8081
  db:
    networks:
      skynet:
        ipv4_address: 10.0.1.100
    container_name: postgresql_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: "/var/lib/postgresql/data/pgdata"
      #POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
networks:
  skynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
volumes:
  db-data:
  pgadmin-data: